# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='uid',
            field=models.CharField(default=0, max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
