# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interaction_system', '0003_auto_20170116_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=60)),
                ('state', models.CharField(blank=True, max_length=60)),
                ('country', models.CharField(blank=True, max_length=60)),
                ('continent', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='address',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='city',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='country',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='state_province',
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interaction_system.Location'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='interaction_system.Location'),
            preserve_default=False,
        ),
    ]
