# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interaction_system', '0006_auto_20170117_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('continent', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interaction_system.Geo'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interaction_system.Geo'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
