# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interaction_system', '0007_auto_20170117_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='location',
        ),
    ]
