# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 12:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interaction_system', '0008_auto_20170117_1744'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Geo',
        ),
    ]
