# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 13:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interaction_system', '0011_auto_20170117_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookUID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid_type', models.CharField(choices=[('ISBN10', 'ISBN10'), ('ISBN13', 'ISBN13'), ('ASIN', 'Amazon UID')], max_length=10)),
                ('uid', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_name', models.CharField(max_length=60)),
                ('qualification_stream', models.CharField(max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='author',
            name='email',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publication_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='qualification_stream',
        ),
        migrations.AddField(
            model_name='author',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='interaction_system.Location'),
        ),
        migrations.AddField(
            model_name='book',
            name='publication_year',
            field=models.SmallIntegerField(default=1000, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(4)]),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='book',
            name='uid',
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='highest_qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interaction_system.Qualification'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reading_frequency',
            field=models.CharField(choices=[(5, 'Almost Never (0-5 times a year)'), (15, 'Sometimes (6-15 times a year)'), (50, 'Few times a month (Once a week)'), (150, 'Few times a week (2-4 times a week)'), (300, 'Almost Everyday (6 times a week)')], max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='uid',
            field=models.ManyToManyField(to='interaction_system.BookUID'),
        ),
    ]
