# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interaction_system', '0012_auto_20170117_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='highest_qualification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='interaction_system.Qualification'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='qualification_name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='qualification_stream',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
