# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 06:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interaction_system', '0015_auto_20170118_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_ratings',
        ),
    ]
