# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 07:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interaction_system', '0016_remove_book_book_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookrating',
            name='rating',
        ),
        migrations.AlterUniqueTogether(
            name='bookrating',
            unique_together=set([('user', 'book')]),
        ),
    ]
