# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction_system', '0017_auto_20170118_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrating',
            name='rating',
            field=models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
        ),
    ]
