# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 09:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interaction_system', '0018_bookrating_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorLikeDislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.SmallIntegerField(choices=[(-1, -1), (0, 0), (1, 1)], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interaction_system.Author')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookLikeDislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.SmallIntegerField(choices=[(-1, -1), (0, 0), (1, 1)], default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interaction_system.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='booklikedislike',
            unique_together=set([('user', 'book')]),
        ),
        migrations.AlterUniqueTogether(
            name='authorlikedislike',
            unique_together=set([('user', 'author')]),
        ),
    ]
