# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('interaction_system', '0019_auto_20170118_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
        migrations.RenameModel(
            old_name='Profile',
            new_name='UserProfile',
        ),
        migrations.RemoveField(
            model_name='book',
            name='tags',
        ),
        migrations.AddField(
            model_name='bookprofile',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='interaction_system.Book'),
        ),
        migrations.AddField(
            model_name='bookprofile',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
